name: Daily Auto Post

on:
  schedule:
    - cron: '0 11 * * *'   # 14:00 МСК
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install aiogram

      - name: Run Python script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

          CHANNEL_ID_1: ${{ secrets.CHANNEL_ID_1 }}
          THREAD_ID_1: ${{ secrets.THREAD_ID_1 }}

          CHANNEL_ID_2: ${{ secrets.CHANNEL_ID_2 }}
          THREAD_ID_2: ${{ secrets.THREAD_ID_2 }}

          CHANNEL_ID_3: ${{ secrets.CHANNEL_ID_3 }}
          THREAD_ID_3: ${{ secrets.THREAD_ID_3 }}

        run: python main.py
